apiVersion: apps/v1
kind: Deployment
metadata:
  name: solidity-security-docs
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: docs-server
        resources:
          requests:
            memory: "96Mi"
            cpu: "75m"
          limits:
            memory: "192Mi"
            cpu: "250m"
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: NODE_ENV
          value: "staging"
        - name: ENVIRONMENT
          value: "staging"
      - name: search-indexer
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
      nodeSelector:
        environment: staging