apiVersion: v1
kind: ConfigMap
metadata:
  name: solidity-security-docs-config
data:
  # Server Configuration
  HTTP_PORT: "3000"
  SEARCH_PORT: "3001"
  BIND_ADDRESS: "0.0.0.0"

  # Application Configuration
  LOG_LEVEL: "info"
  NODE_ENV: "production"
  ENVIRONMENT: "production"

  # Documentation Configuration
  DOCS_TITLE: "Solidity Security Platform Documentation"
  DOCS_DESCRIPTION: "Comprehensive documentation for the Solidity Security Platform"
  DOCS_VERSION: "1.0.0"
  BASE_URL: "/"

  # Search Configuration
  ENABLE_SEARCH: "true"
  SEARCH_PROVIDER: "elasticsearch"
  SEARCH_INDEX_NAME: "solidity-docs"
  ELASTICSEARCH_URL: "http://localhost:9200"
  SEARCH_RESULTS_LIMIT: "20"

  # Static Site Generation
  SSG_ENABLED: "true"
  BUILD_OUTPUT_DIR: "/app/dist"
  STATIC_ASSETS_DIR: "/app/public"

  # Content Configuration
  CONTENT_DIR: "/app/docs"
  MARKDOWN_EXTENSIONS: "tables,code-highlight,mermaid,katex"
  ENABLE_LIVE_RELOAD: "false"

  # Navigation Configuration
  SIDEBAR_AUTO_GENERATE: "true"
  BREADCRUMB_ENABLED: "true"
  TOC_ENABLED: "true"
  TOC_MAX_DEPTH: "3"

  # Theme Configuration
  THEME: "solidity-security"
  DARK_MODE_ENABLED: "true"
  SYNTAX_HIGHLIGHTING: "prism"

  # Social and SEO
  SOCIAL_LINKS: '{"github":"https://github.com/solidity-security","docs":"https://docs.solidity-security.com"}'
  SEO_ENABLED: "true"
  SITEMAP_ENABLED: "true"

  # Performance Configuration
  CACHE_ENABLED: "true"
  CACHE_TTL: "3600"
  COMPRESSION_ENABLED: "true"
  CDN_ENABLED: "false"

  # Health Check Configuration
  HEALTH_CHECK_INTERVAL: "30"
  READINESS_CHECK_TIMEOUT: "5"

  # Metrics Configuration
  ENABLE_METRICS: "true"
  METRICS_PORT: "3000"
  METRICS_PATH: "/metrics"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: solidity-security-docs-content
data:
  # This would contain the documentation markdown files
  # Typically populated during the build process
  index.md: |
    # Solidity Security Platform Documentation

    Welcome to the comprehensive documentation for the Solidity Security Platform.

    ## Quick Start

    Get started with analyzing your Solidity contracts for security vulnerabilities.

    ## Features

    - Multi-tool integration (Slither, Aderyn, MythX, Solidity-Metrics)
    - Advanced intelligence engine for deduplication and risk scoring
    - Real-time notifications and reporting
    - Comprehensive API for automation

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: solidity-security-docs-assets
data:
  # Static assets like CSS, JS, images
  # This would be populated during the build process