# Redis Deployment TLS Volume Mount Patch
# Version: 1.0.0
# Sprint 14 Task 14.8

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: redis-local
spec:
  template:
    spec:
      containers:
      - name: redis
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis
          readOnly: true
        - name: redis-data
          mountPath: /data
        - name: tmp
          mountPath: /tmp
        - name: tls-certs
          mountPath: /etc/redis/certs
          readOnly: true
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
      - name: redis-data
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: tls-certs
        secret:
          secretName: redis-tls
          defaultMode: 0600
