# Redis Configuration with TLS Encryption
# Version: 1.0.0
# Sprint 14 Task 14.8

apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis-local
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: infrastructure-cache
    app.kubernetes.io/part-of: solidity-security-platform
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/instance: local-redis
    app.kubernetes.io/version: "7.2-alpine"
    environment: local
    team: infrastructure
data:
  redis.conf: |-
    # Redis Configuration for Local Development with TLS
    bind 0.0.0.0

    # Disable non-TLS port
    port 0

    # Enable TLS on standard port
    tls-port 6379

    # TLS Configuration
    tls-cert-file /etc/redis/certs/tls.crt
    tls-key-file /etc/redis/certs/tls.key
    tls-ca-cert-file /etc/redis/certs/ca.crt

    # Don't require client certificates (password auth is enough)
    tls-auth-clients no
    tls-protocols "TLSv1.2 TLSv1.3"
    tls-ciphers DEFAULT:!MEDIUM:!LOW:!aNULL:!eNULL:!NULL:!RC4:!MD5:!3DES
    tls-ciphersuites TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256
    tls-prefer-server-ciphers yes

    # Enable password authentication via command line

    # Memory management
    maxmemory 200mb
    maxmemory-policy allkeys-lru

    # Persistence (disabled for local development)
    save ""

    # Logging
    loglevel notice

    # Security
    protected-mode yes

    # Performance
    tcp-keepalive 300
    timeout 0

    # Disable potentially dangerous commands
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    rename-command SHUTDOWN REDIS_SHUTDOWN

    # Enable keyspace notifications for session management
    notify-keyspace-events Ex
