apiVersion: v1
kind: ConfigMap
metadata:
  name: solidity-security-docs-config
data:
  # Production Configuration
  LOG_LEVEL: "info"
  NODE_ENV: "production"
  ENVIRONMENT: "production"

  # Production URLs
  BASE_URL: "https://docs.solidity-security.com"

  # Production settings
  CACHE_TTL: "3600"
  SEARCH_RESULTS_LIMIT: "20"
  CDN_ENABLED: "true"

  # Production performance
  COMPRESSION_ENABLED: "true"
  ENABLE_LIVE_RELOAD: "false"
  ENABLE_DEBUG_ENDPOINTS: "false"

  # Production monitoring
  ENABLE_METRICS: "true"
  SEO_ENABLED: "true"
  SITEMAP_ENABLED: "true"