apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: solidity-security-docs-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: solidity-security-docs
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_container_name]
      targetLabel: container
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'nodejs_.*'
      action: drop