apiVersion: apps/v1
kind: Deployment
metadata:
  name: solidity-security-docs
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: docs-server
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: NODE_ENV
          value: "development"
        - name: ENVIRONMENT
          value: "local"
        - name: ENABLE_LIVE_RELOAD
          value: "true"
      - name: search-indexer
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"